cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

website/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from formapp.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/',login,name='login'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^post/new/$',post_new, name='post_new'),
    url(r'^$',index,name='index'),
    url(r'^delete/(\d+)/$',delete,name='delete'),
    url(r'^search/$',search),
    url(r'^detail/(\d+)/$',detail,name='detail'),
    url(r'^edit/(\d+)/$',edit,name='edit'),
    url(r'^register/$',register,name='register'),
    url(r'^auth_check/$',auth_view,name='check'),
    url(r'^logged_in/$',loggedin),
    url(r'^invalid/$',invalid),
    url(r'^logout/$',logout),
    url(r'^profile/$',profile,name='profile'),
    url(r'^password/$',password,name='password'),
    url(r'^post/$',post,name='post'),
    url(r'^profiledisp/$',profiledisp,name='profiledisp'),
    url(r'^about/$',about,name='about'),
    url(r'^contact/$',contact,name='contact'),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$',post, name='post_list_by_tag'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^category/(?P<category_slug>[-\w]+)/$',post, name='list_of_post_by_category')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

formapp/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from taggit.managers import TaggableManager
from django.conf import settings
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def get_absolute_url(self):
        return reverse('list_of_post_by_category', args=[self.slug])
    
    def __str__(self):
        return self.name
    
class Post(models.Model):
    user=models.ForeignKey(User,blank=True,null=True)
    title=models.CharField(max_length=50)
    content=RichTextUploadingField()
    pic=models.ImageField(upload_to='pic',null=True,blank=True)
    ratings = GenericRelation(Rating, related_query_name='posts')
    category = models.ForeignKey(Category, blank=True)
    tags = TaggableManager(blank=True)
    date_created=models.DateTimeField(default=timezone.now,null=True,blank=True)
    moderated = models.BooleanField(default=False)
    def __unicode__(self):
        return self.title
    @property
    def total_likes(self):
        return self.likes.count()

class Profile(models.Model):
    user=models.OneToOneField(User)
    location=models.CharField(max_length=50,null=True,blank=True)
    gender_choices= (('M', 'Male'), ('F', 'Female'))
    gender = models.CharField(max_length=1, choices=gender_choices)
    profilepic=models.FileField(upload_to='pic',null=True,blank=True,default='pic/def.png')
    bio=models.CharField(max_length=100,null=True,blank=True)
    facebook=models.URLField(null=True,blank=True)
    twitter=models.URLField(null=True,blank=True)
    instagram=models.URLField(null=True,blank=True)
    
    class Meta:
        db_table='auth_profile'

    def __unicode__(self):
        return self.location

def create_user_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)

def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

post_save.connect(create_user_profile,sender=User)
post_save.connect(save_user_profile,sender=User)

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    #email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

formapp/views.py
from django.shortcuts import *
from django.http import *
from .models import *
from .forms import *
from django.views.decorators.http import require_GET
from django.contrib.auth.forms import UserCreationForm
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from taggit.models import Tag
from common.decorators import ajax_required
from django.views.decorators.http import require_POST
# Create your views here.

#OR

def index(request):
    data=Post.objects.filter(Q(moderated=True)).order_by('-date_created')
    data1=Post.objects.filter(ratings__isnull=False).order_by('ratings__average')[:3]
    cat=Tag.objects.all()
    paginator = Paginator(data, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,'allposts.html',{'page': page,'posts': posts,'data1':data1,'cat':cat})

def delete(request,pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return HttpResponseRedirect('/post/')

def search(request):
    cat=Tag.objects.all()
    if request.method=='POST':
        squery=request.POST['search_box']
        if squery:
            data=Post.objects.filter(Q(title__icontains=squery)|Q(content__icontains=squery)|Q(user__username__exact=squery))#i=ignorecase and Q means query
            paginator = Paginator(data, 3) # 3 posts in each page
            page = request.GET.get('page')
            try:
                posts = paginator.page(page)
            except PageNotAnInteger:
                # If page is not an integer deliver the first page
                posts = paginator.page(1)
            except EmptyPage:
                # If page is out of range deliver last page of results
                posts = paginator.page(paginator.num_pages)
            if data:
                return render(request,'allposts.html',{'page': page,'posts': posts,'cat':cat})
            else:
                return render(request,'allposts.html',{'msg':'No Matching Search Result','cat':cat})
        else:
            return HttpResponseRedirect('/post/')

def detail(request,pk):
    post = get_object_or_404(Post, pk=pk)
        # List of active comments for this post
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, 'detail.html', {'post': post,'comments': comments,
'comment_form': comment_form})


def edit(request,pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method=='POST':
        form=PostForm(request.POST,request.FILES,instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.date_created = timezone.now()
            post.save()
            form.save_m2m()
            form.save()
            return HttpResponseRedirect('/post/')
    else:
        form=PostForm(instance=post)
    return render(request,'edit.html',{'form':form})

def register(request):
    if request.method=='POST':
        #form=UserCreationForm(request.POST)   #built in form
        form=Regforms(request.POST)   #user created form
        #built in form usercreationform and table is user
        if form.is_valid():
            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            profile.profilepic='pic/def.png'
            
            User.objects.create_user(username=form.cleaned_data['username'],
                                     email=form.cleaned_data['email'],
                                     password=form.cleaned_data['password'])
            user = auth.authenticate(username=username, password=password)
            auth.login(request, user)
            return HttpResponseRedirect('/login/')
    else:
        #form=UserCreationForm()
        form=Regforms()
    return render(request,'register.html',{'form':form})
@login_required
def profile(request):
    user=request.user
    if request.method=='POST':
        #form=UserCreationForm(request.POST)   #built in form
        form=MyProfile(request.POST,request.FILES)   #user created form
        #built in form usercreationform and table is user
        if form.is_valid():
            user.first_name=form.cleaned_data.get('first_name')
            user.last_name=form.cleaned_data.get('last_name')
            user.profile.location=form.cleaned_data.get('location')
            user.profile.bio=form.cleaned_data.get('bio')
            user.profile.gender=form.cleaned_data.get('gender')
            user.email=form.cleaned_data.get('email')
            user.profile.profilepic=form.cleaned_data['profilepic']
            user.profile.facebook=form.cleaned_data.get('facebook')
            user.profile.twitter=form.cleaned_data.get('twitter')
            user.profile.instagram=form.cleaned_data.get('instagram')
            user.save()
            return redirect('/post/')
    else:
        form=MyProfile(instance=user,initial={
            'location':user.profile.location,
            'gender':user.profile.gender,   
            'facebook':user.profile.facebook,
            'twitter':user.profile.twitter,
            'instagram':user.profile.instagram,
            'bio':user.profile.bio,
            'profilepic':user.profile.profilepic
            })
    return render(request,'profile.html',{'form':form})

def password(request):
    user=request.user
    if request.method=='POST':
        form =Password(request.POST)
        if form.is_valid():
            new_password=form.cleaned_data['new_password']
            user.set_password(new_password)
            user.save()
            return redirect('login')
    else:
        form=Password()
    return render(request,'password.html',{'form':form})
        

def login(request):
    return render(request,'login.html')

def auth_view(request):
    uname=request.POST['uname']
    passw=request.POST['passw']
    user=auth.authenticate(username=uname,password=passw)
    if user is not None:
        auth.login(request,user)
        return HttpResponseRedirect('/logged_in/')
    else:
        return HttpResponseRedirect('/invalid/')

def loggedin(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/post/')
    else:
        return HttpResponse('Page not Found....!')

def invalid(request):
    return render(request,'invalid.html')
    
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')
    
def post(request,tag_slug=None,category_slug=None):
    data=Post.objects.filter(Q(moderated=True)).order_by('-date_created')
    data1=Post.objects.filter(ratings__isnull=False).order_by('ratings__average')[:3]
    cat=Tag.objects.all()
    paginator = Paginator(data, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    categories = Category.objects.all()
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        data = data.filter(tags__in=[tag])
        paginator = Paginator(data, 3) # 3 posts in each page
        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer deliver the first page
            posts = paginator.page(1)
        except EmptyPage:
            # If page is out of range deliver last page of results
            posts = paginator.page(paginator.num_pages)
        return render(request,'allposts.html',{'page': page,'posts': posts,'data1':data1,'tag':tag,'cat':cat})
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        data = data.filter(category=category)
        paginator = Paginator(data, 3) # 3 posts in each page
        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer deliver the first page
            posts = paginator.page(1)
        except EmptyPage:
            # If page is out of range deliver last page of results
            posts = paginator.page(paginator.num_pages)
        return render(request,'allposts.html',{'page': page,'posts': posts,'data1':data1,'category':category,'cat':cat})
    return render(request,'allposts.html',{'page': page,'posts': posts,'data1':data1,'cat':cat})
    

@login_required()
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.date_created = timezone.now()
            post.save()
            form.save_m2m()
            return redirect('detail', post.pk)
    else:
        form = PostForm()
    return render(request, 'post_edit.html', {'form': form})
@login_required

formapp/templates/allposts.html
{% extends 'base.html' %}
{% block head %}
<title> ReviewHub - Your Perfect Destination For Book and Movie Reviews </title>
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
{% endblock %}


{% block content %}
<div class="container pull-right" style="font-size: 20;margin-top: 60px; width: 300px;text-align: center; height: 180px;background-color: #FFFFFF;border-radius: 4px;margin-right: 10">
<p>Subscribe To Our Newsletter</p><p style="margin-top: -15" >&</p>
<p style="font-family: 'Lobster', cursive;margin-top: -15">ASSESS BEFORE YOU POSSESS</p>
<form>
    <div class="input-group">
        <input type="email" class="form-control" required="required" placeholder="E-mail">
        <span class="input-group-btn">
            <button style="font-size: 20px" class="btn btn-default" type="submit"><i class="fa fa-send"></i></button>
        </span>
    </div>
</form>
</div>
<div class="scrollbar border-0 rounded pull-right" id="style-1" style="margin-top: 260px;width: 300px;margin-right: -300">
<div style="height: 60px;background-color: #F8F8F8;font-size: 1.7em;text-align: center;"><p>Browse Reviews</p><p style="font-size: 20;margin-top: -15px">(GENRE)</p></div>
  <div class="force-overflow">
    <ul class="list-group">
    {% for i in cat %}
      <li class="list-group-item"><a href="/tag/{{i.slug}}">{{i.name}}</a></li>
      {% endfor %}
    </ul>
  </div>
</div>
<br>
 {% if data1 %}
 {% if not tag %}
 {% if not category %}
 <h1 style="margin-left: -10%;margin-top: 50px;color: #1B1B1F;font-family: 'Lobster', cursive;font-size: 50px;">Now Trending</h1><br><br>
<div id="slider" style="margin-left: 15%;margin-top: -30px;">
  <a href="#" class="control_next">>></a>
  <a href="#" class="control_prev"><</a>
  <ul>
  {% for i in data1 %}
    <li><a href="{% url 'detail' i.pk %}"><img src="{{i.pic.url}}" height="300px" width="225px"></a></li>
  {% endfor %}</a>
  </ul>  
</div>
{% endif %}
{% endif %}
{% endif %}

{% if tag %}
   <ul><h2 style="margin-left: 18%;margin-top: 5%;color: white">Posts tagged with "{{ tag.name }}"</h2></ul>
{% endif %}

{% if category %}
   <h2 style="margin-left: 18%;margin-top: 5%;color: white"><ul>Posts in category "{{ category.name }}"</ul></h2>
{% endif %}



{% if posts %}
{% for i in posts %}
{% if i.moderated is True %}
<div style="position:relative;top:40px;width:600px;height:220px;margin-left:15%;background-color: white;">
{% if i.pic %}
<div> <a href="{% url 'detail' i.pk %}"><img src="{{i.pic.url}}" height="219px" width="150px" style="border:1px solid black;"></a></div>
{% endif %}
<div style="position: relative;top: -220px;left: 170px;"><a href="{% url 'detail' i.pk %}"><font style="text-transform: uppercase;color: black;font-size: 1.9em;font-family: monospace;">{{i.title}}</font></a></div>
<div style="position: relative;top: -210px;left: 170px;"><font style="text-transform: capitalize;color: black;font-size: 0.8em;font-style: italic;font-family: cursive;">Review By - {{i.user}}</font></div>
<div style="position: relative;top: -225px;left: 390px;"><font style="text-transform: capitalize;color: black;font-size: 0.8em;">Category:{% for category in i.categories %}
{% if not forloop.last %}, {% endif %}

   {% endfor %}<a href="{% url "list_of_post_by_category" i.category.slug %}">{{i.category}}</a>
</font></div>
<div style="position: relative;top: -225px;left: 390px;"><font style="text-transform: capitalize;color: black;font-size: 0.8em;">Tags: {% for tag in i.tags.all %}

       <a href="{% url "post_list_by_tag" tag.slug %}">{{ tag.name }}</a>

       {% if not forloop.last %}, {% endif %}

   {% endfor %}</font></div>

<div style="position: relative;left:175px;top:-220px;width:400px;height: 150px;"><p>{{i.content|truncatewords:30|striptags|safe}}</p><a href="{% url 'detail' i.pk %}" style="position:static; float: right;">Read Full Review ></a></div>
</div>
</div>
<div style="position: relative;width: 600px;margin-left:15%;top: 70px;"><hr style="background-color: #fff;
	border-top: 2px solid #8c8b8b;"></div>
{% endif %} 
{% endfor %}
{% endif %}
{% if msg %}
<h1 style="left: 0;line-height: 200px;margin: auto;margin-top: -100px;position: absolute;top: 50%;width: 100%;">{{msg}}</h1>
{% endif %}
<br>
<br>
{% if posts %}
<h4 style="margin-left: 33%;color: white;">{% include "pagination.html" with page=posts %}</h4>
{% endif %}
<script>
jQuery(document).ready(function ($) {

  setInterval(function () {
    moveRight();
}, 3000);
  
  var slideCount = $('#slider ul li').length;
  var slideWidth = $('#slider ul li').width();
  var slideHeight = $('#slider ul li').height();
  var sliderUlWidth = slideCount * slideWidth;
  
  $('#slider').css({ width: slideWidth, height: slideHeight });
  
  $('#slider ul').css({ width: sliderUlWidth, marginLeft: - slideWidth });
  
    $('#slider ul li:last-child').prependTo('#slider ul');

    function moveLeft() {
        $('#slider ul').animate({
            left: + slideWidth
        }, 200, function () {
            $('#slider ul li:last-child').prependTo('#slider ul');
            $('#slider ul').css('left', '');
        });
    };

    function moveRight() {
        $('#slider ul').animate({
            left: - slideWidth
        }, 200, function () {
            $('#slider ul li:first-child').appendTo('#slider ul');
            $('#slider ul').css('left', '');
        });
    };

    $('a.control_prev').click(function () {
        moveLeft();
    });

    $('a.control_next').click(function () {
        moveRight();
    });

});    

</script>
{% endblock %}

formapp/templates/contact.html
<html>
<head>
	<title>Profile</title>
	<link href="/static/css/bootstrap.min.css"  rel="stylesheet"> 
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="/static/social.css"  rel="stylesheet">
</head>
<body background="https://cdn3.tnwcdn.com/wp-content/blogs.dir/1/files/2015/04/colortheory.jpg">
<div style="width:400px;height:550px;margin-left:37%;margin-top:5% ;border:5px solid silver ;padding:40px 40px;background-color: white">
<center><img src="2.jpg" class="img-circle" width="150px" height="150px" border="2px"></center>
<center>F</center>
<hr style="border-width: 5px;border-color: teal">
<center>
<div style="background-color: #E1F7DB">
<b>{{request.user.profile.bio}}</b><br><br>
<b>First Name: Bhavini</b><br>
<b>Last Name: Sharma</b><br>
<b>Mail me at: bhavini_sharma98@yahoo.com</b><br>
<b>Location:Delhi</b><br><br>
<a class="fa fa-facebook" href="https://www.facebook.com/sharmabhavini"> </a>
<a class="fa fa-twitter" href="https://twitter.com/"> </a>
<a class="fa fa-instagram" href="https://twitter.com/"> </a><br><br>
<a name="post">
</body>
</html>

formapp/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% load ratings %}
{% block head %}
<title>{{post.title}}</title>
<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
{% endblock %}

{% block content %}
<div style="width:800px;height:auto;margin-left:23.5%;margin-top:80px ;border:5px solid silver ;padding:30px 40px;background-color: white;padding-bottom: -300px;">
<center><font style="font-size: 2.5em;"><b><u>{{post.title}}</u></b></font></center>
<div style="position: relative;left: 220px;width:200px;margin-top:10px;">
{% if post.pic %}
<img src="{{post.pic.url}}" height="300" width="250">
{% endif %}<br><br>
</div>
<center>{% ratings post %}</center>

<div style="position: relative;left: auto;top:auto;height:auto;width:auto; ">
 <h3 style="text-align: justify;font-family: 'Cormorant Upright';font-size: 22px;">{{post.content|safe}}</h3>
</div>
<center>
<div style="position: relative;left: 10px;top:auto;">
{% ifequal post.user request.user %}
<a href='/delete/{{post.pk}}/'  class="btn btn-primary btn-md"> Delete</a> 
<a href='/edit/{{post.pk}}/' class="btn btn-primary btn-md">Edit</a>
{% endifequal %}
</div>
</center>
</div>
</div>
 </div>
 </div>
 <div class="container" style="background-color: #FAFAFA;width: 800px;height: auto;margin-bottom: 10;margin-top: 10;border:5px solid silver ;margin-left: 23.5%">
{% with comments.count as total_comments %}
        <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}
    
    {% for comment in comments %}
        <div style=" width: 600px;border:2px solid silver ;margin-bottom: 5px;margin-top: 5px;border-radius: 2px;">
            <h5 style="margin-top: 5px;">&nbsp;<u><b>{{ comment.name }}</b> on {{ comment.created }}</u></h5>
            &nbsp;{{ comment.body }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}
    
    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
        <div style="height: auto;">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p style="margin-left: 36px;"><input type="submit" class="btn btn-success" value="Add comment"></p>
            </div>
        </form>
        
    {%  endif %}

    </div>
    <script src=" http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js "></script>
    <script>
       /*-- like button --*/


$(document).ready(function() {
$('button').on('click', function() {
  // change button type by clicking
  $('.heart-shaped').toggle();

  // initailize
  var rand = Math.floor((Math.random() * 100) + 1);
  var flows = ["flows"];
  var colors = ["heart-particle-col"];
  var timing = (1.3).toFixed(1);

  // Animate Particle
  $('<div class="heart-particle part-' + rand + ' ' + colors[Math.floor((Math.random()))] + '" style="font-size:' + Math.floor(Math.random() * (36 - 12)) + 'px;"><i class="fa fa-heart"></i><i class="fa fa-heart"></i></div>').appendTo('.heart-particle-box').css({
    animation: "" + flows[Math.floor((Math.random()))] + " " + timing + "s linear"
  });
  $('.part-' + rand).show();
  // Remove Particle
  setTimeout(function() {
    $('.part-' + rand).remove();
  }, timing * 1000 - 100);
});
});


/* like counting */
$(document).ready(function() {
    $('.post-likes').click(function() {
        var id;
        id = $(this).attr('data-post-id');
        $.get('/like-blog/', {
            post_id: id
        }, function(data) {
            $('.like_count_blog').html(data);
        });
    });
});</script>
{% endblock %}

formapp/templates/form.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
{% get_comment_form for post.id as form %}
<!-- A context variable called form is created with the necessary hidden
fields, timestamps and security hashes -->
<table>
  <form action="{% comment_form_target %}" method="post">
    {% csrf_token %}
    {{ form }}
    <tr>
      <td colspan="2">
        <input type="submit" name="submit" value="Post">
        <input type="submit" name="preview" value="Preview">
      </td>
    </tr>
  </form>
</table>
</body>
</html>

formapp/templates/profiledisp.html
{% extends 'base.html' %}
{% block head %}
<title> Profile </title> 
{% endblock %}

{% block content %}
<div style="width:400px;height:550px;margin-left:37%;margin-top:5% ;border:5px solid silver ;padding:40px 40px;background-color: white">
{% if request.user.profile.profilepic %}
<center><img src="{{request.user.profile.profilepic.url}}" class="img-circle" width="150px" height="150px" border="2px"></center>
{% endif %}
<center>{{request.user.profile.gender}}</center>
<hr style="border-width: 5px;border-color: teal">
<center>
<div style="background-color: #E1F7DB">
<b>{{request.user.profile.bio}}</b><br><br>
<b>First Name: {{request.user.first_name}}</b><br>
<b>Last Name: {{request.user.last_name}}</b><br>
<b>Mail me at: {{request.user.email}}</b><br>
<b>Location:{{request.user.profile.location}}</b><br><br>
{% if request.user.profile.facebook %}
<a class="fa fa-facebook" href="{{request.user.profile.facebook}}"> </a>
{% endif %}
{% if request.user.profile.twitter %}
<a class="fa fa-twitter" href="{{request.user.profile.twitter}}"> </a>
{% endif %}
{% if request.user.profile.instagram %}
<a class="fa fa-instagram" href="{{request.user.profile.instagram}}"> </a><br><br>
{% endif %}
</div>
<a href="#post" class="btn btn-primary btn-md" style="margin-top: 10px;">View My Posts</a><br>
</div><br><br></center>
<a name="post">
<div class="col-sm-12">
     <div class="thumbnail">
     <div class="caption">
{% for k in request.user.post_set.all %}
<div>
<h1 style="color: red">Title:</h1> {{k.title}}
</div>
<div>
<h1 style="color: red">Review:</h1> {{k.content|safe}}<br><br>
</div>
{% if k.pic %}
Pic: <img src="{{k.pic.url}}" height="200px" width="200px"><br><br>
{% endif %}<br><br>
{% endfor %}

</div>
</div>
</div>
</a>
{% endblock %}